[project]
authors = ["Felix <felixknispel@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "natsec"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
polars = ">=1.27.1,<2"
sqlalchemy = ">=2.0.40,<3"
psycopg2 = ">=2.9.9,<3"
tqdm = ">=4.67.1,<5"
pandas = ">=2.2.3,<3"
pyarrow = ">=19.0.1,<20"
duckdb = ">=1.2.2,<2"
notebook = ">=7.4.1,<8"
